/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanPlaqueRouteImport } from './routes/scan-plaque'
import { Route as OrNouveauRouteImport } from './routes/or.nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanPlaqueRoute = ScanPlaqueRouteImport.update({
  id: '/scan-plaque',
  path: '/scan-plaque',
  getParentRoute: () => rootRouteImport,
} as any)
const OrNouveauRoute = OrNouveauRouteImport.update({
  id: '/or/nouveau',
  path: '/or/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/or/nouveau': typeof OrNouveauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/or/nouveau': typeof OrNouveauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/or/nouveau': typeof OrNouveauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scan-plaque' | '/or/nouveau'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scan-plaque' | '/or/nouveau'
  id: '__root__' | '/' | '/scan-plaque' | '/or/nouveau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScanPlaqueRoute: typeof ScanPlaqueRoute
  OrNouveauRoute: typeof OrNouveauRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-plaque': {
      id: '/scan-plaque'
      path: '/scan-plaque'
      fullPath: '/scan-plaque'
      preLoaderRoute: typeof ScanPlaqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/or/nouveau': {
      id: '/or/nouveau'
      path: '/or/nouveau'
      fullPath: '/or/nouveau'
      preLoaderRoute: typeof OrNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScanPlaqueRoute: ScanPlaqueRoute,
  OrNouveauRoute: OrNouveauRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
