/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExpertisesRouteImport } from './routes/expertises'
import { Route as OrdresRouteImport } from './routes/ordres'
import { Route as ScanPlaqueRouteImport } from './routes/scan-plaque'
import { Route as TourVehiculeRouteImport } from './routes/tour-vehicule'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as ApiTestEmailRouteImport } from './routes/api/test-email'
import { Route as BaseIndexRouteImport } from './routes/base.index'
import { Route as BaseClientsRouteImport } from './routes/base.clients'
import { Route as BaseImportRouteImport } from './routes/base.import'
import { Route as BaseVehiculesRouteImport } from './routes/base.vehicules'
import { Route as CarrosserieIndexRouteImport } from './routes/carrosserie.index'
import { Route as CarrosserieCaseIdRouteImport } from './routes/carrosserie.$caseId'
import { Route as CarrosserieImportRouteImport } from './routes/carrosserie.import'
import { Route as CarrosserieNouvelleRouteImport } from './routes/carrosserie.nouvelle'
import { Route as CarrosserieReferentielsRouteImport } from './routes/carrosserie.referentiels'
import { Route as ClientClientIdRouteImport } from './routes/client.$clientId'
import { Route as ExpertisePartageTokenRouteImport } from './routes/expertise-partage.$token'
import { Route as ExpertiseBaremeRouteImport } from './routes/expertise.bareme'
import { Route as ExpertiseNouvelleRouteImport } from './routes/expertise.nouvelle'
import { Route as MagasinIndexRouteImport } from './routes/magasin.index'
import { Route as MagasinReturnIdRouteImport } from './routes/magasin.$returnId'
import { Route as MagasinAvoirsRouteImport } from './routes/magasin.avoirs'
import { Route as MagasinNouveauRouteImport } from './routes/magasin.nouveau'
import { Route as OrOrIdRouteImport } from './routes/or.$orId'
import { Route as OrNouveauRouteImport } from './routes/or.nouveau'
import { Route as PartageTokenRouteImport } from './routes/partage.$token'
import { Route as VehiculeVehIdRouteImport } from './routes/vehicule.$vehId'
import { Route as BaseCorrectionsImportIdRouteImport } from './routes/base.corrections.$importId'
import { Route as BaseHistoriqueIndexRouteImport } from './routes/base.historique.index'
import { Route as BaseHistoriqueImportIdRouteImport } from './routes/base.historique.$importId'
import { Route as ExpertiseExIdIndexRouteImport } from './routes/expertise.$exId.index'
import { Route as ExpertiseExIdRapportRouteImport } from './routes/expertise.$exId.rapport'
import { Route as TourTourIdIndexRouteImport } from './routes/tour.$tourId.index'
import { Route as TourTourIdPresentationRouteImport } from './routes/tour.$tourId.presentation'
import { Route as TourTourIdRapportRouteImport } from './routes/tour.$tourId.rapport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesRoute = ExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdresRoute = OrdresRouteImport.update({
  id: '/ordres',
  path: '/ordres',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanPlaqueRoute = ScanPlaqueRouteImport.update({
  id: '/scan-plaque',
  path: '/scan-plaque',
  getParentRoute: () => rootRouteImport,
} as any)
const TourVehiculeRoute = TourVehiculeRouteImport.update({
  id: '/tour-vehicule',
  path: '/tour-vehicule',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestEmailRoute = ApiTestEmailRouteImport.update({
  id: '/api/test-email',
  path: '/api/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/base/',
  path: '/base/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseClientsRoute = BaseClientsRouteImport.update({
  id: '/base/clients',
  path: '/base/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseImportRoute = BaseImportRouteImport.update({
  id: '/base/import',
  path: '/base/import',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseVehiculesRoute = BaseVehiculesRouteImport.update({
  id: '/base/vehicules',
  path: '/base/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosserieIndexRoute = CarrosserieIndexRouteImport.update({
  id: '/carrosserie/',
  path: '/carrosserie/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosserieCaseIdRoute = CarrosserieCaseIdRouteImport.update({
  id: '/carrosserie/$caseId',
  path: '/carrosserie/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosserieImportRoute = CarrosserieImportRouteImport.update({
  id: '/carrosserie/import',
  path: '/carrosserie/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosserieNouvelleRoute = CarrosserieNouvelleRouteImport.update({
  id: '/carrosserie/nouvelle',
  path: '/carrosserie/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosserieReferentielsRoute = CarrosserieReferentielsRouteImport.update({
  id: '/carrosserie/referentiels',
  path: '/carrosserie/referentiels',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientClientIdRoute = ClientClientIdRouteImport.update({
  id: '/client/$clientId',
  path: '/client/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisePartageTokenRoute = ExpertisePartageTokenRouteImport.update({
  id: '/expertise-partage/$token',
  path: '/expertise-partage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseBaremeRoute = ExpertiseBaremeRouteImport.update({
  id: '/expertise/bareme',
  path: '/expertise/bareme',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseNouvelleRoute = ExpertiseNouvelleRouteImport.update({
  id: '/expertise/nouvelle',
  path: '/expertise/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const MagasinIndexRoute = MagasinIndexRouteImport.update({
  id: '/magasin/',
  path: '/magasin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagasinReturnIdRoute = MagasinReturnIdRouteImport.update({
  id: '/magasin/$returnId',
  path: '/magasin/$returnId',
  getParentRoute: () => rootRouteImport,
} as any)
const MagasinAvoirsRoute = MagasinAvoirsRouteImport.update({
  id: '/magasin/avoirs',
  path: '/magasin/avoirs',
  getParentRoute: () => rootRouteImport,
} as any)
const MagasinNouveauRoute = MagasinNouveauRouteImport.update({
  id: '/magasin/nouveau',
  path: '/magasin/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const OrOrIdRoute = OrOrIdRouteImport.update({
  id: '/or/$orId',
  path: '/or/$orId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrNouveauRoute = OrNouveauRouteImport.update({
  id: '/or/nouveau',
  path: '/or/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const PartageTokenRoute = PartageTokenRouteImport.update({
  id: '/partage/$token',
  path: '/partage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculeVehIdRoute = VehiculeVehIdRouteImport.update({
  id: '/vehicule/$vehId',
  path: '/vehicule/$vehId',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseCorrectionsImportIdRoute = BaseCorrectionsImportIdRouteImport.update({
  id: '/base/corrections/$importId',
  path: '/base/corrections/$importId',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseHistoriqueIndexRoute = BaseHistoriqueIndexRouteImport.update({
  id: '/base/historique/',
  path: '/base/historique/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseHistoriqueImportIdRoute = BaseHistoriqueImportIdRouteImport.update({
  id: '/base/historique/$importId',
  path: '/base/historique/$importId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseExIdIndexRoute = ExpertiseExIdIndexRouteImport.update({
  id: '/expertise/$exId/',
  path: '/expertise/$exId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseExIdRapportRoute = ExpertiseExIdRapportRouteImport.update({
  id: '/expertise/$exId/rapport',
  path: '/expertise/$exId/rapport',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTourIdIndexRoute = TourTourIdIndexRouteImport.update({
  id: '/tour/$tourId/',
  path: '/tour/$tourId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTourIdPresentationRoute = TourTourIdPresentationRouteImport.update({
  id: '/tour/$tourId/presentation',
  path: '/tour/$tourId/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTourIdRapportRoute = TourTourIdRapportRouteImport.update({
  id: '/tour/$tourId/rapport',
  path: '/tour/$tourId/rapport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expertises': typeof ExpertisesRoute
  '/ordres': typeof OrdresRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/tour-vehicule': typeof TourVehiculeRoute
  '/tours': typeof ToursRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/base/clients': typeof BaseClientsRoute
  '/base/import': typeof BaseImportRoute
  '/base/vehicules': typeof BaseVehiculesRoute
  '/carrosserie/$caseId': typeof CarrosserieCaseIdRoute
  '/carrosserie/import': typeof CarrosserieImportRoute
  '/carrosserie/nouvelle': typeof CarrosserieNouvelleRoute
  '/carrosserie/referentiels': typeof CarrosserieReferentielsRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/expertise-partage/$token': typeof ExpertisePartageTokenRoute
  '/expertise/bareme': typeof ExpertiseBaremeRoute
  '/expertise/nouvelle': typeof ExpertiseNouvelleRoute
  '/magasin/$returnId': typeof MagasinReturnIdRoute
  '/magasin/avoirs': typeof MagasinAvoirsRoute
  '/magasin/nouveau': typeof MagasinNouveauRoute
  '/or/$orId': typeof OrOrIdRoute
  '/or/nouveau': typeof OrNouveauRoute
  '/partage/$token': typeof PartageTokenRoute
  '/vehicule/$vehId': typeof VehiculeVehIdRoute
  '/base/': typeof BaseIndexRoute
  '/carrosserie/': typeof CarrosserieIndexRoute
  '/magasin/': typeof MagasinIndexRoute
  '/base/corrections/$importId': typeof BaseCorrectionsImportIdRoute
  '/base/historique/$importId': typeof BaseHistoriqueImportIdRoute
  '/expertise/$exId/rapport': typeof ExpertiseExIdRapportRoute
  '/tour/$tourId/presentation': typeof TourTourIdPresentationRoute
  '/tour/$tourId/rapport': typeof TourTourIdRapportRoute
  '/base/historique/': typeof BaseHistoriqueIndexRoute
  '/expertise/$exId/': typeof ExpertiseExIdIndexRoute
  '/tour/$tourId/': typeof TourTourIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expertises': typeof ExpertisesRoute
  '/ordres': typeof OrdresRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/tour-vehicule': typeof TourVehiculeRoute
  '/tours': typeof ToursRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/base/clients': typeof BaseClientsRoute
  '/base/import': typeof BaseImportRoute
  '/base/vehicules': typeof BaseVehiculesRoute
  '/carrosserie/$caseId': typeof CarrosserieCaseIdRoute
  '/carrosserie/import': typeof CarrosserieImportRoute
  '/carrosserie/nouvelle': typeof CarrosserieNouvelleRoute
  '/carrosserie/referentiels': typeof CarrosserieReferentielsRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/expertise-partage/$token': typeof ExpertisePartageTokenRoute
  '/expertise/bareme': typeof ExpertiseBaremeRoute
  '/expertise/nouvelle': typeof ExpertiseNouvelleRoute
  '/magasin/$returnId': typeof MagasinReturnIdRoute
  '/magasin/avoirs': typeof MagasinAvoirsRoute
  '/magasin/nouveau': typeof MagasinNouveauRoute
  '/or/$orId': typeof OrOrIdRoute
  '/or/nouveau': typeof OrNouveauRoute
  '/partage/$token': typeof PartageTokenRoute
  '/vehicule/$vehId': typeof VehiculeVehIdRoute
  '/base': typeof BaseIndexRoute
  '/carrosserie': typeof CarrosserieIndexRoute
  '/magasin': typeof MagasinIndexRoute
  '/base/corrections/$importId': typeof BaseCorrectionsImportIdRoute
  '/base/historique/$importId': typeof BaseHistoriqueImportIdRoute
  '/expertise/$exId/rapport': typeof ExpertiseExIdRapportRoute
  '/tour/$tourId/presentation': typeof TourTourIdPresentationRoute
  '/tour/$tourId/rapport': typeof TourTourIdRapportRoute
  '/base/historique': typeof BaseHistoriqueIndexRoute
  '/expertise/$exId': typeof ExpertiseExIdIndexRoute
  '/tour/$tourId': typeof TourTourIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expertises': typeof ExpertisesRoute
  '/ordres': typeof OrdresRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/tour-vehicule': typeof TourVehiculeRoute
  '/tours': typeof ToursRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/base/clients': typeof BaseClientsRoute
  '/base/import': typeof BaseImportRoute
  '/base/vehicules': typeof BaseVehiculesRoute
  '/carrosserie/$caseId': typeof CarrosserieCaseIdRoute
  '/carrosserie/import': typeof CarrosserieImportRoute
  '/carrosserie/nouvelle': typeof CarrosserieNouvelleRoute
  '/carrosserie/referentiels': typeof CarrosserieReferentielsRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/expertise-partage/$token': typeof ExpertisePartageTokenRoute
  '/expertise/bareme': typeof ExpertiseBaremeRoute
  '/expertise/nouvelle': typeof ExpertiseNouvelleRoute
  '/magasin/$returnId': typeof MagasinReturnIdRoute
  '/magasin/avoirs': typeof MagasinAvoirsRoute
  '/magasin/nouveau': typeof MagasinNouveauRoute
  '/or/$orId': typeof OrOrIdRoute
  '/or/nouveau': typeof OrNouveauRoute
  '/partage/$token': typeof PartageTokenRoute
  '/vehicule/$vehId': typeof VehiculeVehIdRoute
  '/base/': typeof BaseIndexRoute
  '/carrosserie/': typeof CarrosserieIndexRoute
  '/magasin/': typeof MagasinIndexRoute
  '/base/corrections/$importId': typeof BaseCorrectionsImportIdRoute
  '/base/historique/$importId': typeof BaseHistoriqueImportIdRoute
  '/expertise/$exId/rapport': typeof ExpertiseExIdRapportRoute
  '/tour/$tourId/presentation': typeof TourTourIdPresentationRoute
  '/tour/$tourId/rapport': typeof TourTourIdRapportRoute
  '/base/historique/': typeof BaseHistoriqueIndexRoute
  '/expertise/$exId/': typeof ExpertiseExIdIndexRoute
  '/tour/$tourId/': typeof TourTourIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/expertises'
    | '/ordres'
    | '/scan-plaque'
    | '/tour-vehicule'
    | '/tours'
    | '/utilisateurs'
    | '/api/test-email'
    | '/base/clients'
    | '/base/import'
    | '/base/vehicules'
    | '/carrosserie/$caseId'
    | '/carrosserie/import'
    | '/carrosserie/nouvelle'
    | '/carrosserie/referentiels'
    | '/client/$clientId'
    | '/expertise-partage/$token'
    | '/expertise/bareme'
    | '/expertise/nouvelle'
    | '/magasin/$returnId'
    | '/magasin/avoirs'
    | '/magasin/nouveau'
    | '/or/$orId'
    | '/or/nouveau'
    | '/partage/$token'
    | '/vehicule/$vehId'
    | '/base/'
    | '/carrosserie/'
    | '/magasin/'
    | '/base/corrections/$importId'
    | '/base/historique/$importId'
    | '/expertise/$exId/rapport'
    | '/tour/$tourId/presentation'
    | '/tour/$tourId/rapport'
    | '/base/historique/'
    | '/expertise/$exId/'
    | '/tour/$tourId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/expertises'
    | '/ordres'
    | '/scan-plaque'
    | '/tour-vehicule'
    | '/tours'
    | '/utilisateurs'
    | '/api/test-email'
    | '/base/clients'
    | '/base/import'
    | '/base/vehicules'
    | '/carrosserie/$caseId'
    | '/carrosserie/import'
    | '/carrosserie/nouvelle'
    | '/carrosserie/referentiels'
    | '/client/$clientId'
    | '/expertise-partage/$token'
    | '/expertise/bareme'
    | '/expertise/nouvelle'
    | '/magasin/$returnId'
    | '/magasin/avoirs'
    | '/magasin/nouveau'
    | '/or/$orId'
    | '/or/nouveau'
    | '/partage/$token'
    | '/vehicule/$vehId'
    | '/base'
    | '/carrosserie'
    | '/magasin'
    | '/base/corrections/$importId'
    | '/base/historique/$importId'
    | '/expertise/$exId/rapport'
    | '/tour/$tourId/presentation'
    | '/tour/$tourId/rapport'
    | '/base/historique'
    | '/expertise/$exId'
    | '/tour/$tourId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/expertises'
    | '/ordres'
    | '/scan-plaque'
    | '/tour-vehicule'
    | '/tours'
    | '/utilisateurs'
    | '/api/test-email'
    | '/base/clients'
    | '/base/import'
    | '/base/vehicules'
    | '/carrosserie/$caseId'
    | '/carrosserie/import'
    | '/carrosserie/nouvelle'
    | '/carrosserie/referentiels'
    | '/client/$clientId'
    | '/expertise-partage/$token'
    | '/expertise/bareme'
    | '/expertise/nouvelle'
    | '/magasin/$returnId'
    | '/magasin/avoirs'
    | '/magasin/nouveau'
    | '/or/$orId'
    | '/or/nouveau'
    | '/partage/$token'
    | '/vehicule/$vehId'
    | '/base/'
    | '/carrosserie/'
    | '/magasin/'
    | '/base/corrections/$importId'
    | '/base/historique/$importId'
    | '/expertise/$exId/rapport'
    | '/tour/$tourId/presentation'
    | '/tour/$tourId/rapport'
    | '/base/historique/'
    | '/expertise/$exId/'
    | '/tour/$tourId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExpertisesRoute: typeof ExpertisesRoute
  OrdresRoute: typeof OrdresRoute
  ScanPlaqueRoute: typeof ScanPlaqueRoute
  TourVehiculeRoute: typeof TourVehiculeRoute
  ToursRoute: typeof ToursRoute
  UtilisateursRoute: typeof UtilisateursRoute
  ApiTestEmailRoute: typeof ApiTestEmailRoute
  BaseClientsRoute: typeof BaseClientsRoute
  BaseImportRoute: typeof BaseImportRoute
  BaseVehiculesRoute: typeof BaseVehiculesRoute
  CarrosserieCaseIdRoute: typeof CarrosserieCaseIdRoute
  CarrosserieImportRoute: typeof CarrosserieImportRoute
  CarrosserieNouvelleRoute: typeof CarrosserieNouvelleRoute
  CarrosserieReferentielsRoute: typeof CarrosserieReferentielsRoute
  ClientClientIdRoute: typeof ClientClientIdRoute
  ExpertisePartageTokenRoute: typeof ExpertisePartageTokenRoute
  ExpertiseBaremeRoute: typeof ExpertiseBaremeRoute
  ExpertiseNouvelleRoute: typeof ExpertiseNouvelleRoute
  MagasinReturnIdRoute: typeof MagasinReturnIdRoute
  MagasinAvoirsRoute: typeof MagasinAvoirsRoute
  MagasinNouveauRoute: typeof MagasinNouveauRoute
  OrOrIdRoute: typeof OrOrIdRoute
  OrNouveauRoute: typeof OrNouveauRoute
  PartageTokenRoute: typeof PartageTokenRoute
  VehiculeVehIdRoute: typeof VehiculeVehIdRoute
  BaseIndexRoute: typeof BaseIndexRoute
  CarrosserieIndexRoute: typeof CarrosserieIndexRoute
  MagasinIndexRoute: typeof MagasinIndexRoute
  BaseCorrectionsImportIdRoute: typeof BaseCorrectionsImportIdRoute
  BaseHistoriqueImportIdRoute: typeof BaseHistoriqueImportIdRoute
  ExpertiseExIdRapportRoute: typeof ExpertiseExIdRapportRoute
  TourTourIdPresentationRoute: typeof TourTourIdPresentationRoute
  TourTourIdRapportRoute: typeof TourTourIdRapportRoute
  BaseHistoriqueIndexRoute: typeof BaseHistoriqueIndexRoute
  ExpertiseExIdIndexRoute: typeof ExpertiseExIdIndexRoute
  TourTourIdIndexRoute: typeof TourTourIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises': {
      id: '/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof ExpertisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordres': {
      id: '/ordres'
      path: '/ordres'
      fullPath: '/ordres'
      preLoaderRoute: typeof OrdresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-plaque': {
      id: '/scan-plaque'
      path: '/scan-plaque'
      fullPath: '/scan-plaque'
      preLoaderRoute: typeof ScanPlaqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-vehicule': {
      id: '/tour-vehicule'
      path: '/tour-vehicule'
      fullPath: '/tour-vehicule'
      preLoaderRoute: typeof TourVehiculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-email': {
      id: '/api/test-email'
      path: '/api/test-email'
      fullPath: '/api/test-email'
      preLoaderRoute: typeof ApiTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/': {
      id: '/base/'
      path: '/base'
      fullPath: '/base/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/clients': {
      id: '/base/clients'
      path: '/base/clients'
      fullPath: '/base/clients'
      preLoaderRoute: typeof BaseClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/import': {
      id: '/base/import'
      path: '/base/import'
      fullPath: '/base/import'
      preLoaderRoute: typeof BaseImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/vehicules': {
      id: '/base/vehicules'
      path: '/base/vehicules'
      fullPath: '/base/vehicules'
      preLoaderRoute: typeof BaseVehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrosserie/': {
      id: '/carrosserie/'
      path: '/carrosserie'
      fullPath: '/carrosserie/'
      preLoaderRoute: typeof CarrosserieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrosserie/$caseId': {
      id: '/carrosserie/$caseId'
      path: '/carrosserie/$caseId'
      fullPath: '/carrosserie/$caseId'
      preLoaderRoute: typeof CarrosserieCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrosserie/import': {
      id: '/carrosserie/import'
      path: '/carrosserie/import'
      fullPath: '/carrosserie/import'
      preLoaderRoute: typeof CarrosserieImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrosserie/nouvelle': {
      id: '/carrosserie/nouvelle'
      path: '/carrosserie/nouvelle'
      fullPath: '/carrosserie/nouvelle'
      preLoaderRoute: typeof CarrosserieNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrosserie/referentiels': {
      id: '/carrosserie/referentiels'
      path: '/carrosserie/referentiels'
      fullPath: '/carrosserie/referentiels'
      preLoaderRoute: typeof CarrosserieReferentielsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$clientId': {
      id: '/client/$clientId'
      path: '/client/$clientId'
      fullPath: '/client/$clientId'
      preLoaderRoute: typeof ClientClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise-partage/$token': {
      id: '/expertise-partage/$token'
      path: '/expertise-partage/$token'
      fullPath: '/expertise-partage/$token'
      preLoaderRoute: typeof ExpertisePartageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/bareme': {
      id: '/expertise/bareme'
      path: '/expertise/bareme'
      fullPath: '/expertise/bareme'
      preLoaderRoute: typeof ExpertiseBaremeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/nouvelle': {
      id: '/expertise/nouvelle'
      path: '/expertise/nouvelle'
      fullPath: '/expertise/nouvelle'
      preLoaderRoute: typeof ExpertiseNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magasin/': {
      id: '/magasin/'
      path: '/magasin'
      fullPath: '/magasin/'
      preLoaderRoute: typeof MagasinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magasin/$returnId': {
      id: '/magasin/$returnId'
      path: '/magasin/$returnId'
      fullPath: '/magasin/$returnId'
      preLoaderRoute: typeof MagasinReturnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magasin/avoirs': {
      id: '/magasin/avoirs'
      path: '/magasin/avoirs'
      fullPath: '/magasin/avoirs'
      preLoaderRoute: typeof MagasinAvoirsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magasin/nouveau': {
      id: '/magasin/nouveau'
      path: '/magasin/nouveau'
      fullPath: '/magasin/nouveau'
      preLoaderRoute: typeof MagasinNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/or/$orId': {
      id: '/or/$orId'
      path: '/or/$orId'
      fullPath: '/or/$orId'
      preLoaderRoute: typeof OrOrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/or/nouveau': {
      id: '/or/nouveau'
      path: '/or/nouveau'
      fullPath: '/or/nouveau'
      preLoaderRoute: typeof OrNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partage/$token': {
      id: '/partage/$token'
      path: '/partage/$token'
      fullPath: '/partage/$token'
      preLoaderRoute: typeof PartageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicule/$vehId': {
      id: '/vehicule/$vehId'
      path: '/vehicule/$vehId'
      fullPath: '/vehicule/$vehId'
      preLoaderRoute: typeof VehiculeVehIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/corrections/$importId': {
      id: '/base/corrections/$importId'
      path: '/base/corrections/$importId'
      fullPath: '/base/corrections/$importId'
      preLoaderRoute: typeof BaseCorrectionsImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/historique/': {
      id: '/base/historique/'
      path: '/base/historique'
      fullPath: '/base/historique/'
      preLoaderRoute: typeof BaseHistoriqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/historique/$importId': {
      id: '/base/historique/$importId'
      path: '/base/historique/$importId'
      fullPath: '/base/historique/$importId'
      preLoaderRoute: typeof BaseHistoriqueImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/$exId/': {
      id: '/expertise/$exId/'
      path: '/expertise/$exId'
      fullPath: '/expertise/$exId/'
      preLoaderRoute: typeof ExpertiseExIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/$exId/rapport': {
      id: '/expertise/$exId/rapport'
      path: '/expertise/$exId/rapport'
      fullPath: '/expertise/$exId/rapport'
      preLoaderRoute: typeof ExpertiseExIdRapportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$tourId/': {
      id: '/tour/$tourId/'
      path: '/tour/$tourId'
      fullPath: '/tour/$tourId/'
      preLoaderRoute: typeof TourTourIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$tourId/presentation': {
      id: '/tour/$tourId/presentation'
      path: '/tour/$tourId/presentation'
      fullPath: '/tour/$tourId/presentation'
      preLoaderRoute: typeof TourTourIdPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$tourId/rapport': {
      id: '/tour/$tourId/rapport'
      path: '/tour/$tourId/rapport'
      fullPath: '/tour/$tourId/rapport'
      preLoaderRoute: typeof TourTourIdRapportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExpertisesRoute: ExpertisesRoute,
  OrdresRoute: OrdresRoute,
  ScanPlaqueRoute: ScanPlaqueRoute,
  TourVehiculeRoute: TourVehiculeRoute,
  ToursRoute: ToursRoute,
  UtilisateursRoute: UtilisateursRoute,
  ApiTestEmailRoute: ApiTestEmailRoute,
  BaseClientsRoute: BaseClientsRoute,
  BaseImportRoute: BaseImportRoute,
  BaseVehiculesRoute: BaseVehiculesRoute,
  CarrosserieCaseIdRoute: CarrosserieCaseIdRoute,
  CarrosserieImportRoute: CarrosserieImportRoute,
  CarrosserieNouvelleRoute: CarrosserieNouvelleRoute,
  CarrosserieReferentielsRoute: CarrosserieReferentielsRoute,
  ClientClientIdRoute: ClientClientIdRoute,
  ExpertisePartageTokenRoute: ExpertisePartageTokenRoute,
  ExpertiseBaremeRoute: ExpertiseBaremeRoute,
  ExpertiseNouvelleRoute: ExpertiseNouvelleRoute,
  MagasinReturnIdRoute: MagasinReturnIdRoute,
  MagasinAvoirsRoute: MagasinAvoirsRoute,
  MagasinNouveauRoute: MagasinNouveauRoute,
  OrOrIdRoute: OrOrIdRoute,
  OrNouveauRoute: OrNouveauRoute,
  PartageTokenRoute: PartageTokenRoute,
  VehiculeVehIdRoute: VehiculeVehIdRoute,
  BaseIndexRoute: BaseIndexRoute,
  CarrosserieIndexRoute: CarrosserieIndexRoute,
  MagasinIndexRoute: MagasinIndexRoute,
  BaseCorrectionsImportIdRoute: BaseCorrectionsImportIdRoute,
  BaseHistoriqueImportIdRoute: BaseHistoriqueImportIdRoute,
  ExpertiseExIdRapportRoute: ExpertiseExIdRapportRoute,
  TourTourIdPresentationRoute: TourTourIdPresentationRoute,
  TourTourIdRapportRoute: TourTourIdRapportRoute,
  BaseHistoriqueIndexRoute: BaseHistoriqueIndexRoute,
  ExpertiseExIdIndexRoute: ExpertiseExIdIndexRoute,
  TourTourIdIndexRoute: TourTourIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
