/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExpertisesRouteImport } from './routes/expertises'
import { Route as OrdresRouteImport } from './routes/ordres'
import { Route as ScanPlaqueRouteImport } from './routes/scan-plaque'
import { Route as TourVehiculeRouteImport } from './routes/tour-vehicule'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as ApiTestEmailRouteImport } from './routes/api/test-email'
import { Route as ExpertiseNouvelleRouteImport } from './routes/expertise.nouvelle'
import { Route as OrOrIdRouteImport } from './routes/or.$orId'
import { Route as OrNouveauRouteImport } from './routes/or.nouveau'
import { Route as PartageTokenRouteImport } from './routes/partage.$token'
import { Route as TourTourIdIndexRouteImport } from './routes/tour.$tourId.index'
import { Route as TourTourIdPresentationRouteImport } from './routes/tour.$tourId.presentation'
import { Route as TourTourIdRapportRouteImport } from './routes/tour.$tourId.rapport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesRoute = ExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdresRoute = OrdresRouteImport.update({
  id: '/ordres',
  path: '/ordres',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanPlaqueRoute = ScanPlaqueRouteImport.update({
  id: '/scan-plaque',
  path: '/scan-plaque',
  getParentRoute: () => rootRouteImport,
} as any)
const TourVehiculeRoute = TourVehiculeRouteImport.update({
  id: '/tour-vehicule',
  path: '/tour-vehicule',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestEmailRoute = ApiTestEmailRouteImport.update({
  id: '/api/test-email',
  path: '/api/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseNouvelleRoute = ExpertiseNouvelleRouteImport.update({
  id: '/expertise/nouvelle',
  path: '/expertise/nouvelle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrOrIdRoute = OrOrIdRouteImport.update({
  id: '/or/$orId',
  path: '/or/$orId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrNouveauRoute = OrNouveauRouteImport.update({
  id: '/or/nouveau',
  path: '/or/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const PartageTokenRoute = PartageTokenRouteImport.update({
  id: '/partage/$token',
  path: '/partage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTourIdIndexRoute = TourTourIdIndexRouteImport.update({
  id: '/tour/$tourId/',
  path: '/tour/$tourId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTourIdPresentationRoute = TourTourIdPresentationRouteImport.update({
  id: '/tour/$tourId/presentation',
  path: '/tour/$tourId/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTourIdRapportRoute = TourTourIdRapportRouteImport.update({
  id: '/tour/$tourId/rapport',
  path: '/tour/$tourId/rapport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expertises': typeof ExpertisesRoute
  '/ordres': typeof OrdresRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/tour-vehicule': typeof TourVehiculeRoute
  '/tours': typeof ToursRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/expertise/nouvelle': typeof ExpertiseNouvelleRoute
  '/or/$orId': typeof OrOrIdRoute
  '/or/nouveau': typeof OrNouveauRoute
  '/partage/$token': typeof PartageTokenRoute
  '/tour/$tourId/presentation': typeof TourTourIdPresentationRoute
  '/tour/$tourId/rapport': typeof TourTourIdRapportRoute
  '/tour/$tourId/': typeof TourTourIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expertises': typeof ExpertisesRoute
  '/ordres': typeof OrdresRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/tour-vehicule': typeof TourVehiculeRoute
  '/tours': typeof ToursRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/expertise/nouvelle': typeof ExpertiseNouvelleRoute
  '/or/$orId': typeof OrOrIdRoute
  '/or/nouveau': typeof OrNouveauRoute
  '/partage/$token': typeof PartageTokenRoute
  '/tour/$tourId/presentation': typeof TourTourIdPresentationRoute
  '/tour/$tourId/rapport': typeof TourTourIdRapportRoute
  '/tour/$tourId': typeof TourTourIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/expertises': typeof ExpertisesRoute
  '/ordres': typeof OrdresRoute
  '/scan-plaque': typeof ScanPlaqueRoute
  '/tour-vehicule': typeof TourVehiculeRoute
  '/tours': typeof ToursRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/expertise/nouvelle': typeof ExpertiseNouvelleRoute
  '/or/$orId': typeof OrOrIdRoute
  '/or/nouveau': typeof OrNouveauRoute
  '/partage/$token': typeof PartageTokenRoute
  '/tour/$tourId/presentation': typeof TourTourIdPresentationRoute
  '/tour/$tourId/rapport': typeof TourTourIdRapportRoute
  '/tour/$tourId/': typeof TourTourIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/expertises'
    | '/ordres'
    | '/scan-plaque'
    | '/tour-vehicule'
    | '/tours'
    | '/utilisateurs'
    | '/api/test-email'
    | '/expertise/nouvelle'
    | '/or/$orId'
    | '/or/nouveau'
    | '/partage/$token'
    | '/tour/$tourId/presentation'
    | '/tour/$tourId/rapport'
    | '/tour/$tourId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/expertises'
    | '/ordres'
    | '/scan-plaque'
    | '/tour-vehicule'
    | '/tours'
    | '/utilisateurs'
    | '/api/test-email'
    | '/expertise/nouvelle'
    | '/or/$orId'
    | '/or/nouveau'
    | '/partage/$token'
    | '/tour/$tourId/presentation'
    | '/tour/$tourId/rapport'
    | '/tour/$tourId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/expertises'
    | '/ordres'
    | '/scan-plaque'
    | '/tour-vehicule'
    | '/tours'
    | '/utilisateurs'
    | '/api/test-email'
    | '/expertise/nouvelle'
    | '/or/$orId'
    | '/or/nouveau'
    | '/partage/$token'
    | '/tour/$tourId/presentation'
    | '/tour/$tourId/rapport'
    | '/tour/$tourId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExpertisesRoute: typeof ExpertisesRoute
  OrdresRoute: typeof OrdresRoute
  ScanPlaqueRoute: typeof ScanPlaqueRoute
  TourVehiculeRoute: typeof TourVehiculeRoute
  ToursRoute: typeof ToursRoute
  UtilisateursRoute: typeof UtilisateursRoute
  ApiTestEmailRoute: typeof ApiTestEmailRoute
  ExpertiseNouvelleRoute: typeof ExpertiseNouvelleRoute
  OrOrIdRoute: typeof OrOrIdRoute
  OrNouveauRoute: typeof OrNouveauRoute
  PartageTokenRoute: typeof PartageTokenRoute
  TourTourIdPresentationRoute: typeof TourTourIdPresentationRoute
  TourTourIdRapportRoute: typeof TourTourIdRapportRoute
  TourTourIdIndexRoute: typeof TourTourIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises': {
      id: '/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof ExpertisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordres': {
      id: '/ordres'
      path: '/ordres'
      fullPath: '/ordres'
      preLoaderRoute: typeof OrdresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-plaque': {
      id: '/scan-plaque'
      path: '/scan-plaque'
      fullPath: '/scan-plaque'
      preLoaderRoute: typeof ScanPlaqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-vehicule': {
      id: '/tour-vehicule'
      path: '/tour-vehicule'
      fullPath: '/tour-vehicule'
      preLoaderRoute: typeof TourVehiculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-email': {
      id: '/api/test-email'
      path: '/api/test-email'
      fullPath: '/api/test-email'
      preLoaderRoute: typeof ApiTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/nouvelle': {
      id: '/expertise/nouvelle'
      path: '/expertise/nouvelle'
      fullPath: '/expertise/nouvelle'
      preLoaderRoute: typeof ExpertiseNouvelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/or/$orId': {
      id: '/or/$orId'
      path: '/or/$orId'
      fullPath: '/or/$orId'
      preLoaderRoute: typeof OrOrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/or/nouveau': {
      id: '/or/nouveau'
      path: '/or/nouveau'
      fullPath: '/or/nouveau'
      preLoaderRoute: typeof OrNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partage/$token': {
      id: '/partage/$token'
      path: '/partage/$token'
      fullPath: '/partage/$token'
      preLoaderRoute: typeof PartageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$tourId/': {
      id: '/tour/$tourId/'
      path: '/tour/$tourId'
      fullPath: '/tour/$tourId/'
      preLoaderRoute: typeof TourTourIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$tourId/presentation': {
      id: '/tour/$tourId/presentation'
      path: '/tour/$tourId/presentation'
      fullPath: '/tour/$tourId/presentation'
      preLoaderRoute: typeof TourTourIdPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$tourId/rapport': {
      id: '/tour/$tourId/rapport'
      path: '/tour/$tourId/rapport'
      fullPath: '/tour/$tourId/rapport'
      preLoaderRoute: typeof TourTourIdRapportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExpertisesRoute: ExpertisesRoute,
  OrdresRoute: OrdresRoute,
  ScanPlaqueRoute: ScanPlaqueRoute,
  TourVehiculeRoute: TourVehiculeRoute,
  ToursRoute: ToursRoute,
  UtilisateursRoute: UtilisateursRoute,
  ApiTestEmailRoute: ApiTestEmailRoute,
  ExpertiseNouvelleRoute: ExpertiseNouvelleRoute,
  OrOrIdRoute: OrOrIdRoute,
  OrNouveauRoute: OrNouveauRoute,
  PartageTokenRoute: PartageTokenRoute,
  TourTourIdPresentationRoute: TourTourIdPresentationRoute,
  TourTourIdRapportRoute: TourTourIdRapportRoute,
  TourTourIdIndexRoute: TourTourIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
